### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kairstenfay** [kairstenfay/latex-resume#1]
- [x] Add job description items 
- [ ] Parametrize link color
- [ ] Make certain sections optional with conditional logic, e.g.
```tex
  %- if porfolio != ""
  /url{\VAR{portfolio|e}}
  %- endif
```
